
class MenuItem{
  String _sId;
  String _enName;
  String _name;
  int _rank;

  Autogenerated({String sId, String enName, String name, int rank}) {
    this._sId = sId;
    this._enName = enName;
    this._name = name;
    this._rank = rank;
  }

  String get sId => _sId;
  set sId(String sId) => _sId = sId;
  String get enName => _enName;
  set enName(String enName) => _enName = enName;
  String get name => _name;
  set name(String name) => _name = name;
  int get rank => _rank;
  set rank(int rank) => _rank = rank;

  Autogenerated.fromJson(Map<String, dynamic> json) { // ignore: invalid_constructor_name
    _sId = json['_id'];
    _enName = json['en_name'];
    _name = json['name'];
    _rank = json['rank'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['_id'] = this._sId;
    data['en_name'] = this._enName;
    data['name'] = this._name;
    data['rank'] = this._rank;
    return data;
  }


}